-- liquibase formatted sql

-- changeset Diego_Pimenta:1784587833018-1
CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

-- changeset Diego_Pimenta:1784587833018-2
CREATE TABLE credencial
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login  VARCHAR(255)                            NOT NULL,
    senha  VARCHAR(255)                            NOT NULL,
    perfil SMALLINT                                NOT NULL,
    CONSTRAINT pk_credencial PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1784587833018-3
CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

-- changeset Diego_Pimenta:1784587833018-4
CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

-- changeset Diego_Pimenta:1784587833018-5
ALTER TABLE credencial
    ADD CONSTRAINT uc_credencial_login UNIQUE (login);

-- changeset Diego_Pimenta:1784587833018-6
ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);

