server:
  port: 8080
  servlet:
    context-path: /oficina/v1

spring:
  application:
    name: oficina
  datasource:
    url: jdbc:postgresql://localhost:5432/oficina
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    root: INFO

jwt:
  key: "ZmlhcHBvc3RlY2hhcnF1aXRldHVyYXNvZnR3YXJlZmFzZTE="