-- liquibase formatted sql

-- changeset Diego_Pimenta:1787875359109-1
CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

-- changeset Diego_Pimenta:1787875359109-2
CREATE SEQUENCE IF NOT EXISTS tb_estoque_seq START WITH 1 INCREMENT BY 50;

-- changeset Diego_Pimenta:1787875359109-3
CREATE SEQUENCE IF NOT EXISTS tb_material_seq START WITH 1 INCREMENT BY 50;

-- changeset Diego_Pimenta:1787875359109-4
CREATE TABLE revchanges
(
    rev        BIGINT NOT NULL,
    entityname VARCHAR(255)
);

-- changeset Diego_Pimenta:1787875359109-5
CREATE TABLE revinfo
(
    rev      BIGINT NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

-- changeset Diego_Pimenta:1787875359109-6
CREATE TABLE tb_caixa
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descricao VARCHAR(255)                            NOT NULL,
    valor     DECIMAL(10, 4)                          NOT NULL,
    fluxo     SMALLINT                                NOT NULL,
    origem    SMALLINT                                NOT NULL,
    data      TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    CONSTRAINT pk_tb_caixa PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-7
CREATE TABLE tb_credencial
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login      VARCHAR(255)                            NOT NULL,
    senha      VARCHAR(255)                            NOT NULL,
    usuario_id BIGINT,
    CONSTRAINT pk_tb_credencial PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-8
CREATE TABLE tb_estoque
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    quantidade  INTEGER,
    minimo      INTEGER,
    material_id BIGINT,
    CONSTRAINT pk_tb_estoque PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-9
CREATE TABLE tb_item_material
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    orcamento_id   BIGINT                                  NOT NULL,
    material_id    BIGINT                                  NOT NULL,
    quantidade     INTEGER                                 NOT NULL,
    preco_unitario DECIMAL(10, 4)                          NOT NULL,
    utilizado      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tb_item_material PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-10
CREATE TABLE tb_item_servico
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    orcamento_id   BIGINT                                  NOT NULL,
    servico_id     BIGINT                                  NOT NULL,
    executor_id    BIGINT,
    quantidade     INTEGER                                 NOT NULL,
    preco_unitario DECIMAL(10, 4)                          NOT NULL,
    data_execucao  TIMESTAMP(6) WITHOUT TIME ZONE,
    executado      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_tb_item_servico PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-11
CREATE TABLE tb_material
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    custo     DECIMAL(10, 4),
    valor     DECIMAL(10, 4),
    tipo      VARCHAR(255) NOT NULL,
    CONSTRAINT pk_tb_material PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-12
CREATE TABLE tb_orcamento
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_criacao   TIMESTAMP(6) WITHOUT TIME ZONE,
    data_aprovacao TIMESTAMP(6) WITHOUT TIME ZONE,
    data_conclusao TIMESTAMP(6) WITHOUT TIME ZONE,
    valor          DECIMAL(10, 4)                          NOT NULL,
    ordem_id       BIGINT,
    CONSTRAINT pk_tb_orcamento PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-13
CREATE TABLE tb_ordem
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status         SMALLINT,
    observacoes    VARCHAR(255),
    data_criacao   TIMESTAMP(6) WITHOUT TIME ZONE,
    data_inicio    TIMESTAMP(6) WITHOUT TIME ZONE,
    data_conclusao TIMESTAMP(6) WITHOUT TIME ZONE,
    data_pagamento TIMESTAMP(6) WITHOUT TIME ZONE,
    valor_total    DECIMAL(10, 4)                          NOT NULL,
    responsavel_id BIGINT,
    cliente_id     BIGINT,
    veiculo_id     BIGINT,
    CONSTRAINT pk_tb_ordem PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-14
CREATE TABLE tb_servico
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    descricao VARCHAR(255),
    custo     DECIMAL(10, 4),
    valor     DECIMAL(10, 4),
    duracao   INTEGER,
    CONSTRAINT pk_tb_servico PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-15
CREATE TABLE tb_usuario
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    sobrenome VARCHAR(255),
    email     VARCHAR(255),
    cpfcnpj   VARCHAR(255),
    telefone  VARCHAR(255),
    perfil    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_usuario PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-16
CREATE TABLE tb_veiculo
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    placa          VARCHAR(255),
    montadora      VARCHAR(255),
    modelo         VARCHAR(255),
    cor            VARCHAR(255),
    tipo           SMALLINT,
    chassi         VARCHAR(255),
    ano_fabricacao INTEGER,
    quilometragem  INTEGER,
    CONSTRAINT pk_tb_veiculo PRIMARY KEY (id)
);

-- changeset Diego_Pimenta:1787875359109-17
ALTER TABLE tb_credencial
    ADD CONSTRAINT uc_tb_credencial_login UNIQUE (login);

-- changeset Diego_Pimenta:1787875359109-18
ALTER TABLE tb_credencial
    ADD CONSTRAINT uc_tb_credencial_usuario UNIQUE (usuario_id);

-- changeset Diego_Pimenta:1787875359109-19
ALTER TABLE tb_estoque
    ADD CONSTRAINT uc_tb_estoque_material UNIQUE (material_id);

-- changeset Diego_Pimenta:1787875359109-20
ALTER TABLE tb_credencial
    ADD CONSTRAINT FK_TB_CREDENCIAL_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES tb_usuario (id);

-- changeset Diego_Pimenta:1787875359109-21
ALTER TABLE tb_estoque
    ADD CONSTRAINT FK_TB_ESTOQUE_ON_MATERIAL FOREIGN KEY (material_id) REFERENCES tb_material (id);

-- changeset Diego_Pimenta:1787875359109-22
ALTER TABLE tb_item_material
    ADD CONSTRAINT FK_TB_ITEM_MATERIAL_ON_MATERIAL FOREIGN KEY (material_id) REFERENCES tb_material (id);

-- changeset Diego_Pimenta:1787875359109-23
ALTER TABLE tb_item_material
    ADD CONSTRAINT FK_TB_ITEM_MATERIAL_ON_ORCAMENTO FOREIGN KEY (orcamento_id) REFERENCES tb_orcamento (id);

-- changeset Diego_Pimenta:1787875359109-24
ALTER TABLE tb_item_servico
    ADD CONSTRAINT FK_TB_ITEM_SERVICO_ON_EXECUTOR FOREIGN KEY (executor_id) REFERENCES tb_usuario (id);

-- changeset Diego_Pimenta:1787875359109-25
ALTER TABLE tb_item_servico
    ADD CONSTRAINT FK_TB_ITEM_SERVICO_ON_ORCAMENTO FOREIGN KEY (orcamento_id) REFERENCES tb_orcamento (id);

-- changeset Diego_Pimenta:1787875359109-26
ALTER TABLE tb_item_servico
    ADD CONSTRAINT FK_TB_ITEM_SERVICO_ON_SERVICO FOREIGN KEY (servico_id) REFERENCES tb_servico (id);

-- changeset Diego_Pimenta:1787875359109-27
ALTER TABLE tb_orcamento
    ADD CONSTRAINT FK_TB_ORCAMENTO_ON_ORDEM FOREIGN KEY (ordem_id) REFERENCES tb_ordem (id);

-- changeset Diego_Pimenta:1787875359109-28
ALTER TABLE tb_ordem
    ADD CONSTRAINT FK_TB_ORDEM_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES tb_usuario (id);

-- changeset Diego_Pimenta:1787875359109-29
ALTER TABLE tb_ordem
    ADD CONSTRAINT FK_TB_ORDEM_ON_RESPONSAVEL FOREIGN KEY (responsavel_id) REFERENCES tb_usuario (id);

-- changeset Diego_Pimenta:1787875359109-30
ALTER TABLE tb_ordem
    ADD CONSTRAINT FK_TB_ORDEM_ON_VEICULO FOREIGN KEY (veiculo_id) REFERENCES tb_veiculo (id);

-- changeset Diego_Pimenta:1787875359109-31
ALTER TABLE revchanges
    ADD CONSTRAINT fk_revchanges_on_default_tracking_modified_entities_changelog FOREIGN KEY (rev) REFERENCES revinfo (rev);

